using System.ComponentModel;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using skyscraper5.Skyscraper.Plugins;

namespace skyscraper8.UI.MonoGame.Screenhacks
{
	[PluginPriority(0)]
	[DisplayName("Blank")]
	internal class _0_Blank : IScreenhack
	{
		public void Draw(GameTime gameTime, SpriteBatch spriteBatch, Rectangle windowBounds)
		{
			
		}

		public void SetGraphicsDevice(GraphicsDevice graphicsDevice, Rectangle presentationParametersBounds)
		{
			
		}

		public void Dispose()
		{
			
		}
	}
}
